name: Azure Functions Deploy

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Setup Azure Functions Core Tools
      uses: actions/setup-azure-functions-core-tools@v1
      with:
        version: '3.x'

    - name: Install dependencies
      run: |
        npm install
        npm run build --if-present

    - name: Sign in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Publish to Azure Functions
      run: |
        func azure functionapp publish <FunctionAppName>